deploy:

  needs: build-and-push

  runs-on: ubuntu-latest

  steps:

  - name: Checkout
    uses: actions/checkout@v5

  - name: Setup kubectl
    uses: azure/setup-kubectl@v4

  - name: Configure Kubeconfig
    run: |
      mkdir -p $HOME/.kube
      echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

  - name: Check Cluster
    run: |
      kubectl get nodes
      kubectl get pods

  - name: Deploy
    run: |
      kubectl set image deployment/flask-app \
      flask-app=${{ secrets.DOCKER_USERNAME }}/flask-cicd:${{ github.sha }}

      kubectl rollout status deployment/flask-app --timeout=120s
